const ChallengeStatus  = {
    NEW : 'GAME.NEW_TITLE',
    GUESS_TO_BE_SET : 'GAME.GUESS_TO_BE_SET_TITLE',
    CHALLENGER_TO_MOVE : 'GAME.CHALLENGER_TO_MOVE_TITLE',
    SUCCESS : 'GAME.FINISHED_SUCCESSFULLY_TITLE',
    FAILURE : 'GAME.FINISHED_NOTHING_HAPPENS_TITLE'
};
Object.freeze(ChallengeStatus)
exports.ChallengeStatus = ChallengeStatus;